spring.datasource.url=jdbc:h2:mem:networkmonitor;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

server.port=8080

# ?????? ???????????? (???????????) ? ??? ? 30 ??????
app.scan.interval-ms=30000
app.scan.timeout-ms=1000
app.scan.enabled=true
app.scan.on-startup=true

# ??????? ?????????? ????? ? ?????? 2 ???????
app.ping.interval-ms=2000